- name: Add Microsoft signing key
  become: true
  ansible.builtin.rpm_key:
    key: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Add dnf repositories
  become: true
  loop: "{{ repos }}"
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    file: "{{ item.file }}"
    baseurl: "{{ item.baseurl }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ item.gpgkey }}"
