---
- name: Configure Fedora Workstation
  hosts: localhost
  vars:
    enable_desktop: false
    enable_gaming: false
    download_builtin_ohmyposh_themes: false
  roles:
    - dnf-repository
    - cli
    - shell
    - role: desktop
      when: enable_desktop | bool
    - role: gaming
      when: enable_gaming | bool
