---
- name: Configure Fedora Workstation
  hosts: localhost
  tasks:
    - name: Configure dnf repository
      import_role:
        name: dnf-repository

    - name: Install dnf packages
      import_role:
        name: dnf

    - name: Install Flatpaks
      import_role:
        name: flatpak

    - name: Install Gaming stuff
      import_role:
        name: gaming

    - name: Install oh-my-posh
      import_role:
        name: oh-my-posh

    - name: Install fonts
      import_role:
        name: fonts

    - name: Install and configure zsh
      import_role:
        name: zsh

    - name: Install CLI tools
      import_role:
        name: cli
