---
- name: Configure Fedora Workstation
  hosts: localhost
  tasks:
    - name: Configure dnf repository
      import_role:
        name: dnf-repository

    - name: Install dnf packages
      import_role:
        name: dnf

    - name: Install Flatpaks
      import_role:
        name: flatpak

    - name: Install oh-my-posh
      import_role:
        name: oh-my-posh

    - name: Install fonts
      import_role:
        name: fonts

    - name: Add oh-my-posh to zsh
      copy:
        dest: "/home/{{ ansible_user_id }}/.zshrc"
        content: |
          HISTFILE=~/.histfile
          HISTSIZE=1000
          SAVEHIST=1000
          bindkey -e

          zstyle :compinstall filename '/home/{{ ansible_user_id }}/.zshrc'

          autoload -Uz compinit
          compinit

          eval "$(oh-my-posh init zsh --config ~/.poshthemes/amro.omp.json)"
