- name: Install dnf packages
  become: true
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present

- name: Install Flatpaks
  community.general.flatpak:
    name: "{{ flatpaks }}"
    state: present
