- name: Add WineHQ repository
  become: true
  ansible.builtin.yum_repository:
    name: WineHQ
    description: WineHQ packages
    file: winehq
    baseurl: "https://dl.winehq.org/wine-builds/fedora/36/"
    enabled: yes
    gpgcheck: yes
    gpgkey: "https://dl.winehq.org/wine-builds/winehq.key"

- name: Install Flatpaks
  community.general.flatpak:
    name: "{{ flatpaks }}"
    state: present

- name: Install dnf packages
  become: true
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
