- name: Install Oh-My-Posh (Manual)
  become: true
  get_url:
    url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64
    dest: /usr/local/bin/oh-my-posh
    force: yes
    mode: 0755

- name: Create directory PoshThemes
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/.poshthemes"
    state: directory

- name: Download oh-my-posh themes
  get_url:
    url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip
    dest: "/home/{{ ansible_user_id }}/.poshthemes/themes.zip"

- name: Extract oh-my-posh themes
  ansible.builtin.unarchive:
    src: "/home/{{ ansible_user_id }}/.poshthemes/themes.zip"
    dest: "/home/{{ ansible_user_id }}/.poshthemes"
    mode: u+rw

- name: Set permissions oh-my-posh themes
  become: true
  shell: "chmod u+rw /home/{{ ansible_user_id }}/.poshthemes/*.json"

- name: Remove oh-my-posh themes.zip
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/.poshthemes/themes.zip"
    state: absent
